dist: jammy
language: node_js

node_js:
  - 18
  - 20
  - 22

env:
- MONGO=4.0
- MONGO=4.2
- MONGO=4.4
- MONGO=5.0
- MONGO=6.0
- MONGO=7.0
- MONGO=8.0

services:
- docker

before_script:
  - docker run -d -p 27017:27017 mongo:${MONGO}

script:
  - npm run test

after_script:
  - npm run publish-coverage

cache: npm
