language: node_js

node_js:
  - 8
  - 10

matrix:
  allow_failures:
    - node_js: 10
      env: PACKAGE=baucis MONGOOSE_VERSION=4
env:
# Disabled for now, cf issue: https://github.com/CoorpAcademy/baucis/issues/7
# - PACKAGE=baucis MONGOOSE_VERSION=3.8.x # cf https://github.com/Automattic/mongoose/issues/3436#issuecomment-146198805
- PACKAGE=baucis MONGOOSE_VERSION=4
- PACKAGE=baucis MONGOOSE_VERSION=5
- PACKAGE=baucis-swagger
- PACKAGE=baucis-swagger2
- PACKAGE=baucis-openapi3

services:
- docker

install:
  - if [ $PACKAGE = baucis ] ; then (cd packages/baucis && npm install --save-dev mongoose@$MONGOOSE_VERSION ); fi
  - npm install

before_script:
  - docker-compose up -d

script:
  - npm run lint
  - (cd packages/$PACKAGE && npm run cover)

after_script:
  - npm run publish-coverage

cache:
  directories:
      - node_modules
