language: node_js

node_js:
  - 8
  - 10

matrix:
  allow_failures:
    - node_js: 10
env:
- PACKAGE=baucis
- PACKAGE=baucis-swagger

services:
- docker

install:
  - npm install

before_script:
  - docker-compose up -d

script:
  - npm run lint
  - (cd packages/$PACKAGE && npm run cover)

after_script:
  - npm run publish-coverage

cache:
  directories:
      - node_modules
