language: node_js
node_js:
  - "8"
  - "9"
services:
  - mongodb
after_success:
  - nyc report -r lcov
  - node node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
  - node_modules/.bin/coveralls < coverage/lcov.info